stages:
  - test

variables:
  INSTALL_PACKAGES: git gcc make cmake unzip

test_opensource-1.10:
  stage: test
  tags:
    - docker
  image: centos:7
  before_script:
    - curl -s https://packagecloud.io/install/repositories/tarantool/1_10/script.rpm.sh | bash
    - yum -y install tarantool tarantool-devel
    - tarantool -V
    - yum -y install epel-release
    - yum -y install $INSTALL_PACKAGES
  script:
    - make ci_prepare
    - make lint test


test_opensource-2.x:
  stage: test
  tags:
    - docker
  image: centos:7
  before_script:
    - curl -s https://packagecloud.io/install/repositories/tarantool/2x/script.deb.sh | sudo bash
    - yum -y install tarantool tarantool-devel
    - tarantool -V
    - yum -y install epel-release
    - yum -y install $INSTALL_PACKAGES
  script:
    - make ci_prepare
    - make lint test


test_opensource-2.2:
  stage: test
  tags:
    - docker
  image: centos:7
  before_script:
    - curl -s https://packagecloud.io/install/repositories/tarantool/2_2/script.rpm.sh | bash
    - yum -y install tarantool tarantool-devel
    - tarantool -V
    - yum -y install epel-release
    - yum -y install $INSTALL_PACKAGES
  script:
    - make ci_prepare
    - make lint test