stages:
  - test

.test-opensource: &test-opensource
  stage: test
  tags:
    - docker
  image: centos:7
  before_script:
    - curl -s https://packagecloud.io/install/repositories/tarantool/$TARANTOOL_REPO/script.rpm.sh | bash
    - yum -y install git gcc cmake tarantool tarantool-devel
    - tarantool -V
    - tarantoolctl rocks install luatest 0.3.0
    - tarantoolctl rocks install luacheck 0.25.0
  script:
    - tarantoolctl rocks make
    - make test -C build.luarocks ARGS="-V"

test-opensource-1.10:
  <<: *test-opensource
  variables:
    TARANTOOL_REPO: "1_10"

test-opensource-2.2:
  <<: *test-opensource
  variables:
    TARANTOOL_REPO: "2_2"

test-opensource-2.x:
  <<: *test-opensource
  variables:
    TARANTOOL_REPO: "2x"
